### PR TITLE
Added Group Chat Support + Compatibility for WP mailed chats

### PR DESCRIPTION
**Pull request by rubyAce71697**
Below changes are done as part of this Merge Request

1. Added group supports. 
2. Added support for windows phone mailed chats. Whats app follows different format while mailing chat from windows phone.

Review.

### CODE REVIEW

**Comment by prabhakar267** [comment]
@rubyAce71697 I recently made a few changes in code, can you update the PR according to those changes?

**Comment by rubyAce71697** [comment]
Yeah Okay. I will update it

**Comment by prabhakar267** [comment]
@rubyAce71697  Check the updated Readme file :+1:

**Comment by rubyAce71697** [comment]
WoW! you updated you code and merged. cool!

**Comment by rubyAce71697** [comment]
I think its still broken,
wp chats and windows group chats are giving me 

"It wasn't a valid text file or we were not able to convert it!"

**Comment by prabhakar267** [comment]
It shows this error when it is not able to read the date-time string https://github.com/prabhakar267/whatsapp-reader/blob/master/inc/function.inc.php#L114 here
So i think the regex rule has to be updated

**Comment by rubyAce71697** [comment]
@prabhakar267  The files are not properly merged and not all the updates were applied. It is still not working with wp and group chats. you can check my "edited" branch for more info.
Can you update me with your new flow of the code. I am not quite able to grasp it.

**Pull request merged**
